### ISSUE TITLE
"32-byte entropy are acceptable."

### ISSUE THREAD

**Issue by HamishMacEwan** [jes/bip39tool#1]
Currently bip39tool seems to accept only 16-byte entropy in 32 hex characters.

```
bip39tool/bip39tool -o words EF12DBF98584FE7944B4BD30B61ADE790D6F3C86CE330061EA9CCEB36735C18D
Traceback (most recent call last):
  File "bip39tool/bip39tool", line 96, in <module>
    main(sys.argv[1:])
  File "bip39tool/bip39tool", line 82, in main
    entropy = hexlify(mnemo.to_entropy(inputtxt))
  File "/usr/local/lib/python2.7/dist-packages/mnemonic/mnemonic.py", line 93, in to_entropy
    raise ValueError('Number of words must be one of the following: [12, 15, 18, 21, 24], but it is not (%d).' % len(words))
ValueError: Number of words must be one of the following: [12, 15, 18, 21, 24], but it is not (1).
```

**Comment by jes** [comment]
You're right, fixed now, thanks @HamishMacEwan !

**Comment by HamishMacEwan** [comment]
You're welcome, here, have some hwrng entropy from me: C6B2933002F3A76F80C684E85C600BB86E560F7EECB1002EFA8EA15490A6348E

**Comment by jes** [comment]
In case there's any BTC on an address generated from that entropy: I've failed to find it :)

**Comment by HamishMacEwan** [comment]
It would suprise me to learn that down any of those paths there is even one useful key.

PS, Did you loosen the match? I did to {,64}, oh, you did, to +  :)
